Repository 9oormthon-univ/2025_SEASONTHON_TEAM_71_FE, pull requests merged in 2025-09, with the labels that each got.

#9 Feature#6 login
  package.json
  src/App.jsx
  src/index.css
  src/layout/JoinLayout.jsx
  src/layout/MainLayout.jsx
  src/pages/Home.jsx
  src/pages/Join/Login.jsx
  yarn.lock
Labels: ✨Feature

#11 feature#8 home header
  .yarn/install-state.gz
  package.json
  src/App.jsx
  src/assets/img/main_logo.svg
  src/components/HomeHeader.jsx
  src/layout/MainLayout.jsx
  src/pages/AIConsultant/MatchingLoading.jsx
  src/pages/AIConsultant/MatchingMain.jsx
  src/pages/AIConsultant/MatchingResult.jsx
  src/pages/Home.jsx
  src/pages/Join/Login.jsx
  src/stores/authStore.js
  yarn.lock
Labels: ✨Feature

#15 Feature#12 chat
  src/App.jsx
  src/layout/MainLayout.jsx
  src/pages/AIConsultant/Chat.jsx
  src/styles/MainContainer.style.js
  yarn.lock
Labels: ✨Feature

#17 feature#14-개인-채용공고 관련 3페이지
  .yarn/install-state.gz
  src/App.jsx
  src/assets/img/closebtn.svg
  src/assets/img/ex1.svg
  src/assets/img/ex2.svg
  src/assets/img/readingglasses.svg
  src/components/HomeHeader.jsx
  src/components/JobCard.jsx
  src/pages/AIConsultant/MatchingResult.jsx
  src/pages/Home.jsx
  src/pages/Jobs/JobDetail.jsx
  src/pages/Jobs/JobList.jsx
  src/pages/Join/JoinInfo.jsx
Labels: ✨Feature

#27 api#18 login/signup
  .yarn/install-state.gz
  package.json
  src/api/login.js
  src/api/signup.js
  src/components/HomeHeader.jsx
  src/pages/Join/JoinCategory.jsx
  src/pages/Join/JoinInfo.jsx
  src/pages/Join/Login.jsx
  src/stores/authStore.js
  vite.config.js
  yarn.lock
Labels: 📬 API

#30 bug: role 오류 수정
  src/api/login.js
  src/api/signup.js
  src/components/HomeHeader.jsx
  src/pages/Join/JoinInfo.jsx
  src/pages/Join/Login.jsx
Labels: 🐞Bug

#37 api#35 get job list
  src/api/http.js
  src/api/jobs.js
  src/pages/Jobs/JobList.jsx
Labels: 📬 API
